dataset_name: rgbd
N_samples: 256
N_importance: 256
img_wh: [80, 60]
num_epochs: 5
batch_size: 128
optimizer: adam
lr: 5e-4
lr_scheduler: exp
decay_gamma: 0.9999
exp_name: exp/thin_geometry/
use_sdf: True
color_weight: 10
depth_weight: 1
freespace_weight: 1
truncation_weight: 1
val_check_interval: 0.02
max_val_images: 10
N_emb_dir: 8
N_emb_xyz: 8
share_coarse_fine: True
omni_dir: True
pose_gt: True
perturb: 1
