dataset_name: rgbd
N_samples: 256
N_importance: 256
num_epochs: 15
batch_size: 512
optimizer: adam
lr: 5e-4
lr_scheduler: exp
decay_gamma: 0.9999
exp_name: exp/thin_geometry/
use_sdf: True
color_weight: 30
depth_weight: 20
freespace_weight: 10
truncation_weight: 30
val_check_interval: 0.05
max_val_images: 10
N_emb_dir: 6
N_emb_xyz: 8
share_coarse_fine: True
omni_dir: True
pose_gt: True
perturb: 1
