dataset_name: rgbd
root_dir: ../thin_geometry
N_samples: 512
N_importance: 128
img_wh: [80, 60]
num_epochs: 30
batch_size: 200
optimizer: adam
lr: 5e-4
lr_scheduler: exp
decay_gamma: 0.9999
exp_name: exp/thin_geometry/
val_check_interval: 0.1
max_val_images: 8