dataset_name: rgbd
root_dir: ../thin_geometry
N_samples: 512
N_importance: 32
img_wh: [80, 60]
num_epochs: 30
batch_size: 200
optimizer: adam
lr: 5e-4
lr_scheduler: exp
decay_gamma: 0.9999
exp_name: exp/thin_geometry/
use_sdf: True
color_weight: 50
depth_weight: 50
freespace_weight: 1e7
truncation_weight: 1e8
val_check_interval: 0.1
max_val_images: 10
N_emb_dir: 12
N_emb_xyz: 16
share_coarse_fine: True
omni_dir: True